### ISSUE TITLE
Lavalink server shutting down when left idle for 15 minutes

### ISSUE THREAD

**Issue by pewpasta** [KareemRS/heroku-lavalink#10]
Whenever the server is left idle for more than 15 minutes, it shuts down and gives this error 
`2021-05-11T18:18:43.747853+00:00 app[web.1]: 2021-05-11 18:18:43.747  INFO 32 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketContext         : Shutting down 0 playing players.`

**Comment by karyeet** [comment]
Are you using a service (such as uptime robot) to visit the website in order to prevent Heroku from shutting down the app for inactivity? Do you have a premium app?

**Comment by pewpasta** [comment]
I use a professional Dyno, so I don't think I need to use uptimerobot.
The server can stay up for hours as long as I'm playing music on my bot. But when I stop listening to music on my bot and the Lavalink server becomes idle, the error shows up after 15 minutes and it shuts down.

**Comment by karyeet** [comment]
Unfortunately, the log segment you sent me doesn't tell me anything except that your server shutdown. 
If lavalink is crashing, it may be an upstream issue. 
Try with uptimerobot, if the problem persists submit more logs.
