### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by BrianWasTaken** [KareemRS/heroku-lavalink#11]
Unfortunately, i can't use the server. There are no errors during bootstrap but when I tried connecting my lava manager (I use `erela.js` btw), it shows this error:
```
Node "disgusting-bot.herokuapp.com" encountered an error: read ECONNRESET.
```

is there any way to fix this?

**Comment by karyeet** [comment]
Not sure if you are still having this issue, but I tested with the same library and had no issues connecting or playing.

Ensure your node is properly listed:
```
const nodes = [
  {
    host: "disgusting-bot.herokuapp.com",
    password: "yourpassword",
    port: 80,
  }
];
```
Also make sure both nodejs and erela.js are on highest recommended versions.
