### ISSUE TITLE
Violates Heroku ToS?

### ISSUE THREAD

**Issue by Abadima** [KareemRS/heroku-lavalink#21]
![image](https://user-images.githubusercontent.com/39747270/160824709-dc81a381-1aea-4410-9fdf-f76958f0f816.png)

**Comment by karyeet** [comment]
Not sure.
It seems this specific repository was flagged as I was able to deploy from a random up to date fork.
You can do the same by replacing GITHUB_URL with a link to a fork below.

`https://heroku.com/deploy?template=GITHUB_URL`

I'll see what I can do.

**Comment by karyeet** [comment]
I have created a clone of this repo which will automatically sync the auto branch (current default branch).
The button will deploy from the clone.

This will be my solution unless the clone is also blocked.
