### ISSUE TITLE
can u add a simple get method 

### ISSUE THREAD

**Issue by AriaFantom** [KareemRS/heroku-lavalink#4]
app.get('/',(req,res) => {
return res.send('Hello');
}); like this

**Comment by karyeet** [comment]
May I ask for what?

**Comment by Tari-dev** [comment]
For checking if the server is alive or not

**Comment by karyeet** [comment]
No.
Lavalink is already listening to the port provided by heroku.

However here are two alternatives:
- You hit the website with no Authentication header and check for a 401 response with an empty body.
- You hit the website with a correct Authentication header & check for a 400 response with the body containing "_Can "Upgrade" only to "WebSocket"._"

A downed project on heroku will either not respond or go online when you send a request.
Most, if not all, services like UptimeRobot will work properly with an empty body.
