### ISSUE TITLE
How to get the host’s link

### ISSUE THREAD

**Issue by kakarot-dev** [KareemRS/heroku-lavalink#7]
Ive got the port but what should i put to get the website where it is hosted?

**Comment by karyeet** [comment]
On your project page look to the top right and click open app.
![image](https://user-images.githubusercontent.com/28524112/113180148-3fee3680-9205-11eb-85e1-deb8e3441696.png)

**Comment by ManavvGarg** [comment]
> Ive got the port but what should i put to get the website where it is hosted?

Can ik how did you get the port

**Comment by kakarot-dev** [comment]
honestly i have no idea rn
it was so long ago
